### ISSUE TITLE
Связь с автором

### ISSUE THREAD

**Issue by ioncat** [Rugut/UPP#1]
Здравствуйте, Rugut, заинтересовала ваша работа по 1С + рест, как с вами можно связаться?

**Comment by Rugut** [comment]
Добрый день. Вы уже связались.Спрашивайте. Спасибо.  23.08.2013, 11:50, "ioncat" notifications@github.com:Здравствуйте, заинтересовала ваша работа по 1С + рест, как с вами можно связаться? мой скайп alex.i.bondarenko—Reply to this email directly or view it on GitHub.

**Comment by rus0000** [comment]
Подскажите, а что за объект базы dbo.V82КлассыNet ?
